authentication/urls.py
from django.urls import path
from . import views

urlpatterns = [
    
    path('register',views.registration,name='register'),
    path('admin_registration',views.adminregistration,name='admin_registration'),
    path('login',views.user_login,name='login'),
    path('admin_login',views.admin_login,name='admin_login'),
    path('logout',views.user_logout,name='logout'),
    path('admin_logout',views.admin_logout,name='admin_logout'),
    path('profile/<int:user_id>/', views.user_profile, name='user_profile'),
    path('admin_profile/<int:user_id>/', views.admin_profile, name='admin_profile'),
    path('profile',views.update_profile,name='profile'),

]

mfj/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('intro.urls')),
    path('',include('explore.urls')),
    path('authentication/',include('authentication.urls')),
    path('',include('payment.urls')),
    path('',include('review.urls')),
    path('',include('filter.urls')),
    path('',include('contactus.urls')),
    path('',include('admins.urls')),
    path('',include('appointments.urls')),
    path('',include('appointments.urls')),
    path('',include('bill.urls')),
]

urlpatterns = urlpatterns + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

authentication/models.py
from django.contrib.auth.models import User
from django.db import models

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    username = models.CharField(max_length=50)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    profile_photo = models.ImageField(upload_to='profile_photos', default='default_profile_photo.jpg')

class AdminProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    username = models.CharField(max_length=50)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)

authentication/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.contrib.auth.models import User
from .models import UserProfile, AdminProfile

# User Register

def registration(request):

    if request.method == 'POST':
        username = request.POST[ 'username']
        password1 = request.POST[ 'password1']
        password2 = request.POST[ 'password2']
        first_name = request.POST[ 'first_name']
        last_name = request.POST[ 'last_name']
        email = request.POST['email']

        if password1==password2:
            if User.objects.filter(email=email).exists():
                messages.info(request,'Email ID Taken')
                return redirect('register')
            elif User.objects.filter(username=username).exists():
                messages.info(request,'Username Taken')
                return redirect('register')
            else:
                user = User.objects.create_user (password=password1, email=email,username=username,first_name=first_name,last_name=last_name)
                UserProfile.objects.create(user=user,username=username,email=email, first_name=first_name, last_name=last_name)
                user.save();
                print('user created')
                return redirect('login')
        else:
            messages.info(request,'Password not matching')
            return redirect('register')
        return redirect('/register')
    else:   
        return render(request, 'authentication/register.html')

# user_login

def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('user_profile', user_id=user.id)
        else:
            messages.error(request, 'Invalid credentials')
    return render(request, 'authentication/login.html')

@login_required
def user_profile(request, user_id):
    user = User.objects.get(id=user_id)
    return render(request, 'explore/explore.html', {'user': user})

# user_logout

def user_logout(request):
    logout(request)
    return redirect('/explore')

# profile_view

@login_required
def profile_view(request):
    user_profile = UserProfile.objects.get(user=request.user)
    return render(request, 'authentication/profile.html', {'user_profile': user_profile})

# update_profile

@login_required
def update_profile(request):
    user_profile = UserProfile.objects.get(user=request.user)
    
    if request.method == 'POST':
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        username = request.POST.get('username')
        email = request.POST.get('email')
        profile_photo = request.FILES.get('profile_photo')
        
        user_profile.first_name = first_name
        user_profile.last_name = last_name
        user_profile.username = username
        user_profile.email = email
        user_profile.profile_photo = profile_photo
        user_profile.save()
    
    return render(request, 'authentication/profile.html', {'user_profile': user_profile})

# Admin_register

def adminregistration(request):

    if request.method == 'POST':
        username = request.POST[ 'username']
        password1 = request.POST[ 'password1']
        password2 = request.POST[ 'password2']
        first_name = request.POST[ 'first_name']
        last_name = request.POST[ 'last_name']
        email = request.POST['email']

        if password1==password2:
            if User.objects.filter(email=email).exists():
                messages.info(request,'Email ID Taken')
                return redirect('admin_registration')
            elif User.objects.filter(username=username).exists():
                messages.info(request,'Username Taken')
                return redirect('admin_registration')
            else:
                user = User.objects.create_user (password=password1, email=email,username=username,first_name=first_name,last_name=last_name)
                AdminProfile.objects.create(user=user,username=username,email=email, first_name=first_name, last_name=last_name)
                user.save();
                print('user created')
                return redirect('admin_login')
        else:
            messages.info(request,'Password not matching')
            return redirect('admin_registration')
        return redirect('/admin_registration')
    else:   
        return render(request, 'authentication/admin_registration.html')
    
# user_login

def admin_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('admin_profile', user_id=user.id)
        else:
            messages.error(request, 'Invalid credentials')
    return render(request, 'authentication/admin_login.html')

@login_required
def admin_profile(request, user_id):
    user = User.objects.get(id=user_id)
    return render(request, 'admin/adminhome.html', {'user': user})

# user_logout

def admin_logout(request):
    logout(request)
    return redirect('/explore')

templates/authentication/admin_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <script src="https://cdn.tailwindcss.com"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Title Page-->
    <title>Login</title>

    <!-- Icons font CSS-->
    <link href="{% static 'vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="{% static 'vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/datepicker/daterangepicker.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'css/main.css' %}" rel="stylesheet" media="all">
</head>

<body>
    <div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">
        <div class="wrapper wrapper--w680">
            <div class="card card-4">
                <div class="card-body">
                    <div class="row row-space text-white text-xl mb-8">
                        <a class="bg-gradient-to-r from-pink-600 to-purple-400 rounded-md hover:text-black px-4 py-4" href ="{% url 'admin_login' %}"><h2>Admin Login</h2></a>
                        <a class="bg-gradient-to-r from-pink-600 to-purple-400 rounded-md hover:text-black px-4 py-4" href ="{% url 'login' %}"><h2>User Login</h2></a>
                    </div>
                    <h2 class="title">Admin Login</h2>
                    <form method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <label for="username" class="label">Username</label>
                            <input class="input--style-4" type="text" name="username" required> 
                        </div>  
                        <div class="input-group">
                            <label for="password" class="label">Password</label>
                            <input class="input--style-4" type="Password" name="password" required>
                        </div>
						<div class="row row-space">
                            <div class="col-2">
                        		<div class="p-t-15">
                                    <button class="bg-sky-600 hover:bg-sky-400 px-10 py-3 rounded-md text-white" value="Admin_login" type="submit">Login</button>
                        		</div>
							</div>
							<div class="col-2">
                                {% for message in messages %}
								<p class="text-red-700 text-xl mt-[8%]"> {{message}} </p>
                                {% endfor %}
							</div>
						</div>
                        <div class="row row-space">
                            <p class="mt-[2%] text-grey-700 text-xl">New user? <a href ="{% url 'admin_registration' %}" class="underline underline-offset-auto">Signup</a> </p>
                        </div>                    
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Jquery JS-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <!-- Vendor JS-->
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/moment.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/daterangepicker.js' %}"></script>

    <!-- Main JS-->
    <script src="{% static 'js/global.js' %}"></script>

</body>

</html>
<!-- end document-->

templates/authentication/admin_registration.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <script src="https://cdn.tailwindcss.com"></script>

    <!-- Title Page-->
    <title>Registration</title>

    <!-- Icons font CSS-->
    <link href="{% static 'vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="{% static 'vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/datepicker/daterangepicker.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'css/main.css' %}" rel="stylesheet" media="all">
</head>

<body>
    <div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">
        <div class="wrapper wrapper--w680">
            <div class="card card-4">
                <div class="card-body">
                    <h2 class="title">Admin Signup</h2>
                    <form method="POST" action="admin_registration">
                        {% csrf_token %}
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">first name</label>
                                    <input class="input--style-4" type="text" name="first_name" required>
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">last name</label>
                                    <input class="input--style-4" type="text" name="last_name" required>
                                </div>
                            </div>
                        </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Username</label>
                                    <input class="input--style-4" type="text" name="username" required>
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Email</label>
                                    <input class="input--style-4" type="email" name="email" required>
                                </div>
                            </div>
                        </div>
                        <div class="row row-space">
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Password</label>
                                    <input class="input--style-4" type="Password" name="password1" required>
                                </div>
                            </div>
                            <div class="col-2">
                                <div class="input-group">
                                    <label class="label">Confirm Password</label>
                                    <input class="input--style-4" type="Password" name="password2" required>
                                </div>
                            </div>
                        </div>
						<div class="row row-space">
                            <div class="col-2">
                        		<div class="p-t-15">
                           			<button class="bg-sky-600 hover:bg-sky-400 px-10 py-3 rounded-md text-white" type="submit">Submit</button>
                        		</div>
							</div>
							<div class="col-2">
                                {% for message in messages %}
								<p class="text-red-700 text-xl mt-[8%]"> {{message}} </p>
                                {% endfor %}
							</div>
						</div>
                        <div class="row row-space">
                            <p class="mt-[2%] text-grey-700 text-xl">Already a user ? <a href ="admin_login" class="underline underline-offset-auto">Login</a> </p>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Jquery JS-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <!-- Vendor JS-->
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/moment.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/daterangepicker.js' %}"></script>

    <!-- Main JS-->
    <script src="{% static 'js/global.js' %}"></script>

</body>

</html>
<!-- end document-->

templates/authentication/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title></title>
        <script src="https://cdn.tailwindcss.com"></script>
        <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.16/dist/tailwind.min.css" rel="stylesheet">
        <link rel="stylesheet" href="{% static 'css/search.css' %}">
    </head>
    <body>
        <div class="flex h-screen">
            <!-- Side Navbar -->
            <div class="bg-gradient-to-r from-rose-600 to-purple-700 text-white w-1/4 flex flex-col">
                {% if user.is_authenticated %}
                    <div class="p-4">
                        <h2 class="text-2xl font-bold">Hello, {{user.first_name}}</h2>
                    </div>
                {% endif %}
                <ul class="flex-1 py-4">
                    <li class="px-6 py-3 hover:bg-gradient-to-r from-rose-700 to-purple-800">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-3 inline-block" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6m12 0a9 9 0 110-18 9 9 0 010 18z"></path>
                        </svg>
                        <a href="{% url 'profile' %}">Profile</a> 
                    </li>
                    <li class="px-6 py-3 hover:bg-gradient-to-r from-rose-700 to-purple-800">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-3 inline-block icon icon-tabler icon-tabler-shopping-cart" width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffffff" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                            <path d="M6 19m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" />
                            <path d="M17 19m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" />
                            <path d="M17 17h-11v-14h-2" />
                            <path d="M6 5l14 1l-1 7h-13" />
                        </svg>
                        <a href="{% url 'cart' %}">My cart</a>      
                    </li>
                    <li class="px-6 py-3 hover:bg-gradient-to-r from-rose-700 to-purple-800">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-3 inline-block icon icon-tabler icon-tabler-truck-return" width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffffff" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                            <path d="M7 17m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" />
                            <path d="M17 17m-2 0a2 2 0 1 0 4 0a2 2 0 1 0 -4 0" />
                            <path d="M5 17h-2v-11a1 1 0 0 1 1 -1h9v6h-5l2 2m0 -4l-2 2" />
                            <path d="M9 17l6 0" />
                            <path d="M13 6h5l3 5v6h-2" />
                          </svg>
                        My order
                    </li>
                    <li class="px-6 py-3 hover:bg-gradient-to-r from-rose-700 to-purple-800">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-3 inline-block icon icon-tabler icon-tabler-calendar-stats" width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5" stroke="#ffffff" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                            <path d="M11.795 21h-6.795a2 2 0 0 1 -2 -2v-12a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v4" />
                            <path d="M18 14v4h4" />
                            <path d="M18 18m-4 0a4 4 0 1 0 8 0a4 4 0 1 0 -8 0" />
                            <path d="M15 3v4" />
                            <path d="M7 3v4" />
                            <path d="M3 11h16" />
                          </svg>
                        <a href="{% url 'appointment_list' %}">My Appointments</a>      
                    </li>
                    <li class="px-6 py-3 hover:bg-gradient-to-r from-rose-700 to-purple-800">
                        <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 mr-3 inline-block" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"></path>
                        </svg>
                        Settings
                    </li>
                </ul>
                <div class="p-4">
                    <a href="{% url 'logout' %}">        
                        <button class="bg-gradient-to-r from-rose-800 to-purple-800 px-4 py-2 rounded-full hover:bg-indigo-700">Logout</button>
                    </a>
                </div>
            </div>

            <!-- Main Content -->
            <div class="w-3/4 p-4 bg-gray-100 text-black ">
                <h1 class="text-center mb-5 text-2xl font-bold">Mahila</h1>
                {% block content %}
                {% endblock content %}    
            </div>
        </div>
    </body>
</html>

templates/authentication/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags-->
    <meta charset="UTF-8">
    <script src="https://cdn.tailwindcss.com"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Title Page-->
    <title>Login</title>

    <!-- Icons font CSS-->
    <link href="{% static 'vendor/mdi-font/css/material-design-iconic-font.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/font-awesome-4.7/css/font-awesome.min.css' %}" rel="stylesheet" media="all">
    <!-- Font special for pages-->
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

    <!-- Vendor CSS-->
    <link href="{% static 'vendor/select2/select2.min.css' %}" rel="stylesheet" media="all">
    <link href="{% static 'vendor/datepicker/daterangepicker.css' %}" rel="stylesheet" media="all">

    <!-- Main CSS-->
    <link href="{% static 'css/main.css' %}" rel="stylesheet" media="all">
</head>

<body>
    <div class="page-wrapper bg-gra-02 p-t-130 p-b-100 font-poppins">
        <div class="wrapper wrapper--w680">
            <div class="card card-4">
                <div class="card-body">
                    <div class="row row-space text-white text-xl mb-8">
                        <a class="bg-gradient-to-r from-pink-600 to-purple-400 rounded-md hover:text-black px-4 py-4" href ="{% url 'admin_login' %}"><h2>Admin Login</h2></a>
                        <a class="bg-gradient-to-r from-pink-600 to-purple-400 rounded-md hover:text-black px-4 py-4" href ="{% url 'login' %}"><h2>User Login</h2></a>
                    </div>
                    <h2 class="title">User Login</h2>
                    <form method="post">
                        {% csrf_token %}
                        <div class="input-group">
                            <label for="username" class="label">Username</label>
                            <input class="input--style-4" type="text" name="username" required> 
                        </div>  
                        <div class="input-group">
                            <label for="password" class="label">Password</label>
                            <input class="input--style-4" type="Password" name="password" required>
                        </div>
						<div class="row row-space">
                            <div class="col-2">
                        		<div class="p-t-15">
                                    <button class="bg-sky-600 hover:bg-sky-400 px-10 py-3 rounded-md text-white" value="Login" type="submit">Login</button>
                        		</div>
							</div>
							<div class="col-2">
                                {% for message in messages %}
								<p class="text-red-700 text-xl mt-[8%]"> {{message}} </p>
                                {% endfor %}
							</div>
						</div>
                        <div class="row row-space">
                            <p class="mt-[2%] text-grey-700 text-xl">New user? <a href ="{% url 'register' %}" class="underline underline-offset-auto">Signup</a> </p>
                        </div>                    
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Jquery JS-->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <!-- Vendor JS-->
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/moment.min.js' %}"></script>
    <script src="{% static 'vendor/datepicker/daterangepicker.js' %}"></script>

    <!-- Main JS-->
    <script src="{% static 'js/global.js' %}"></script>

</body>

</html>
<!-- end document-->

templates/authentication/profile.html
{% extends 'authentication/base.html' %}
{% load static %}
{% block content %}
    <div class="flex justify-center items-center">
        <div class="bg-white p-8 rounded-lg shadow-md w-96">
            <form method="post" action="profile" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-4 flex justify-center items-center relative">
                    <div class="relative w-36 h-36 rounded-full overflow-hidden">
                        {% if user_profile.profile_photo %}
                        <img src="{{ user_profile.profile_photo.url }}" alt="Profile Photo" class="w-full h-full object-cover">
                        {% else %}
                        <img src="{% static 'images/explore/default.png' %}" alt="default Photo" class="w-full h-full object-cover">
                        {% endif %}
                    </div>
                    <label for="id_profile_photo" class="bg-white absolute bottom-0 top-18 left-44 p-1 rounded-full cursor-pointer ">
                        <svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-pencil" width="24" height="24" viewBox="0 0 24 24" stroke-width="1.5" stroke="#000000" fill="none" stroke-linecap="round" stroke-linejoin="round">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"/>
                            <path d="M4 20h4l10.5 -10.5a1.5 1.5 0 0 0 -4 -4l-10.5 10.5v4" />
                            <path d="M13.5 6.5l4 4" />
                        </svg>
                        <input type="file" id="id_profile_photo" name="profile_photo" class="hidden" value="{% if user_profile.profile_photo %}{{ user_profile.profile_photo.url }}{% else %}{% static 'images/explore/default.png' %}{% endif %}">
                    </label>
                </div>
                <div class="mb-4">
                    <label class="block text-sm font-medium text-gray-600">Username</label>
                    <input type="text" name="username" class="mt-1 p-2 w-full border rounded-md" value="{{ user_profile.username }}">
                </div>
                <div class="mb-4">
                    <label class="block text-sm font-medium text-gray-600">Email</label>
                    <input type="email" name="email" class="mt-1 p-2 w-full border rounded-md" value="{{ user_profile.email }}">
                </div>
                <div class="grid grid-cols-2 gap-4 mb-4">
                    <div class="mb-4">
                        <label class="block text-sm font-medium text-gray-600">First Name</label>
                        <input type="text" name="first_name" class="mt-1 p-2 w-full border rounded-md" value="{{ user_profile.first_name }}">
                    </div>
                    <div class="mb-4">
                        <label class="block text-sm font-medium text-gray-600">Last Name</label>
                        <input type="text" name="last_name" class="mt-1 p-2 w-full border rounded-md" value="{{ user_profile.last_name }}">
                    </div>
                </div>
                <button type="submit" class="bg-blue-500 text-white py-2 px-4 rounded-md hover:bg-blue-600 focus:outline-none focus:ring focus:ring-blue-200">Save Changes</button>
            </form>
        </div>
    </div>
{% endblock content %}  